# Generated by Django 5.0.1 on 2024-05-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Contact_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/form'),
        ),
    ]
