# Generated by Django 5.0.1 on 2024-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='form/'),
        ),
    ]
