# Generated by Django 5.0.1 on 2024-05-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_service_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_des',
            new_name='service_price',
        ),
    ]
