# Generated by Django 5.0.1 on 2024-05-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_service_des_service_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_icon',
            new_name='service_des',
        ),
    ]
