# Generated by Django 5.0.1 on 2024-05-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_service_icon_service_service_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_des',
            field=models.CharField(max_length=500),
        ),
    ]
