# Generated by Django 5.0.1 on 2024-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_service_service_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_img1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/form'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_img2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/form'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_img3',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/form'),
        ),
    ]
