# Generated by Django 5.0.1 on 2024-05-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chairset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairs_des', models.CharField(max_length=500)),
                ('chairs_title', models.CharField(max_length=50)),
                ('chairs_img', models.FileField(default=None, max_length=250, null=True, upload_to='media/pic')),
                ('chairs_price', models.TextField()),
            ],
        ),
    ]
