# Generated by Django 5.0.1 on 2024-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairset',
            name='chairs_img1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/form'),
        ),
        migrations.AddField(
            model_name='chairset',
            name='chairs_img2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/form'),
        ),
        migrations.AddField(
            model_name='chairset',
            name='chairs_img3',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/form'),
        ),
    ]
